config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages , except: [:index, :new]

end

app/models/message.rb
class Message < ActiveRecord::Base
    # 募集タイトルは必須入力かつ20文字以内
    validates :title , length: { maximum: 50 } , presence: true    
    #　仕事の内容は必須入力かつ2文字以上30文字以下
    validates :body , length: { minimum: 2, maximum: 100 } , presence: true
    #　対象年齢は0以上の数字だけ入力できる
    validates :age , numericality: { only_integer: true, greater_than_or_equal_to: 0} , presence: true
    #　勤務地は必須入力かつ20文字以内
    validates :station , length: { maximum: 30 } , presence: true   
    # 投稿者は必須入力かつ20文字以内
    validates :name , length: { maximum: 30 } , presence: true       
    # 連絡先メールは必須入力かつ20文字以内
    validates :mail , length: { maximum: 40 } , presence: true    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]
  
  def index
    @message = Message.new
    # Messageを全て取得する。
    @messages = Message.all
  end
  
  def create
  @message = Message.new(message_params)
  if @message.save
    redirect_to root_path , notice: 'メッセージを保存しました'
  else
    #　メッセージが保全できなかった時
    @messages = Message.all
    flash.now[:alert] = "メッセージの保存に失敗しました。"
    render 'index'
  end
 end
 
 def edit
 end   
 
 def update
   if @message.update(message_params)
     #保存に成功した場合はトップぺージにリダイレクト
     redirect_to root_path , notice: 'メッセージを編集しました'
    else
      #保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end
  
  def destroy
    @message.destroy
    redirect_to root_path,notice: 'メッセージを削除しました'
  end  
  
  private
  def message_params
    params.require(:message).permit(:title, :body, :age, :station, :name, :mail,)
  end  
  ## ここまで
  
  def set_message
    @message = Message.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>求人募集一覧</title>
  <meta name="keywords" content="求人募集,掲示板,投稿,">
  <meta name="description" content="こちは求人募集用の掲示板です。">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    
<div class="container">
  <div class="page-header">
	  <h1>求人募集掲示板　　<small>JOB Borard</small></h1>
  </div>

 
      
</div>
 
  <div class="container">
     <% if notice %>
        <div class="alert alert-info">
          <%= notice %>
        </div>
      <% end %>
  <%= yield %>
  </div>
  
<footer>
	<div class="copyright">c2016 JOB Borard Inc.</div>
</footer>
  
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message,html:{class:"form-horizontal"}) do |f| %>

  <% if @message.errors.present? %>
    <div class="alert alert-danger">
      <%= alert %>
      <ul>
        <% @message.errors.full_messages.each do |full_message| %>
          <li>
            <%= full_message %>
          </li>
        <% end %> 
      </ul>
    </div>
  <% end %>

<div class="boxin">
  <div class="form-group">
         <div class="col-md-2 control-label"><label for="exampleInputtitle">募集タイトル：</label></div>
         <div class="col-md-10"><%= f.text_field :title,class:"form-control",id:"exampleInputtitle",placeholder:"【急募】　プログラマ―募集" %></div>
  </div>  
  
  <div class="form-group">
         <div class="col-md-2 control-label"><label for="exampleInputbody">仕事の内容：</label></div>
         <div class="col-md-10"><%= f.text_area :body,class:"form-control",id:"exampleInputbody",placeholder:"プログラミング業務など" %></div>
  </div> 
      
  <div class="form-group">
         <div class="col-md-2 control-label"><label for="exampleInputage">対象年齢：</label></div>
         <div class="col-md-1"><%= f.text_field :age,class:"form-control",id:"exampleInputage",placeholder:"20" %></div>
         <div class="col-md-9">歳まで</div>
  </div> 
  
  <div class="form-group">
         <div class="col-md-2 control-label"><label for="exampleInputstation">勤務地：</label></div>
         <div class="col-md-10"><%= f.text_field :station,class:"form-control",id:"exampleInputstation",placeholder:"東京・横浜" %></div>
  </div> 
  
  <div class="form-group">
         <div class="col-md-2 control-label"><label for="exampleInputname">投稿者：</label></div>
         <div class="col-md-4"><%= f.text_field :name,class:"form-control",id:"exampleInputname",placeholder:"田中花子" %></div>
  </div> 
  
  <div class="form-group">
         <div class="col-md-2 control-label"><label for="exampleInputmail">連絡先メール：</label></div>
         <div class="col-md-4"><%= f.text_field :mail,class:"form-control",id:"exampleInputmail",placeholder:"hana@gmial.com" %></div>
  </div> 
  
  <div class="form-group">
    <div class="col-md-2"></div>
    <div class="col-md-10"><%= f.submit "投稿する",  class:"btn btn-primary" %></div>
  </div>
</div>
<% end %>

app/views/messages/edit.html.erb
<div class="alert alert-warning" role="alert"><strong>メッセージの編集</strong></div>

<div class="panel panel-default">
    <div class="panel-body"><%= render 'form' %></div>
</div>

app/views/messages/index.html.erb
<div class="alert alert-success" role="alert"><strong>新規投稿</strong></div>    

<% #部分テンプレートを読み込んでいる　入力欄　%>
<%= render 'form' %>

<div class="mes_des">
  
  <div class="alert alert-danger" role="alert"><strong>求人募集</strong></div>      
  
  <% @messages.each do |message| %>
      
    <div class="panel panel-danger">
      <div class="panel-heading">
        <span class=""><%= message.title%></span>
      </div>
      
      <div class="panel-body">
        <div class="t_but"><span class="label label-default t_but2">仕事の内容</span>　<%= message.body%></div>
        <div class="t_but"><span class="label label-default t_but2">対象年齢</span>　<%= message.age%>歳まで</div>
        <div class="t_but"><span class="label label-default t_but2">勤務地</span>　<%= message.station%></div>
        <div class="t_but"><span class="label label-default t_but2">投稿者</span>　<%= message.name %></div>
        <div class="t_but"><span class="label label-default t_but2">連絡先メール</span>　<%= message.mail%></div>
          <div class="dell">
          <%= link_to "編集する" , edit_message_path(message) , :class => "btn btn-danger" %>
          <%= link_to "削除する" , message , method: :delete, data: { confirm: '削除してもよろしいですか？' } , :class => "btn btn-danger" %></div>
      </div>
    </div>
    
  <% end %>
  
</div>